import { API_URL, customerRequest } from "../../lib/api";
import React,{useEffect,useState} from "react";
import {ArrowLeft,Receipt,Download,RefreshCw} from "lucide-react";
import {useNavigate} from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import "./CustomerReceipts.css";

async function load(){const t=localStorage.getItem("customerToken");const r=await fetch(`${API_URL}/api/customer/orders`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error("Unable to load receipts");return r.json()}
export default function CustomerReceipts(){const nav=useNavigate();const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const refresh=()=>{setLoading(true);load().then(d=>setOrders(Array.isArray(d.orders)?d.orders:[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(refresh,[]);const download=(o)=>{const doc=new jsPDF();doc.setFontSize(20);doc.text("YN STUDIO",20,20);doc.setFontSize(11);doc.text(`Receipt ${o.public_order_number||o.id}`,20,29);autoTable(doc,{startY:40,head:[["Item","Amount"]],body:[[o.service_name||"YN Studio Order",`$${Number(o.total||0).toFixed(2)}`],["Status",o.status||"Pending"]]});doc.save(`receipt-${o.public_order_number||o.id}.pdf`)};return <section className="customer-receipts-page"><button className="receipt-back" onClick={()=>nav(-1)}><ArrowLeft size={18}/> Back</button><div className="receipt-heading"><div><p>FINANCE</p><h1>Receipts</h1><span>Your order payment records</span></div><button onClick={refresh}><RefreshCw size={17}/></button></div>{error&&<div className="receipt-error">{error}</div>}{loading?<div className="receipt-empty">Loading receipts…</div>:orders.length===0?<div className="receipt-empty"><Receipt size={28}/><h2>No receipts yet</h2><p>Completed orders will appear here.</p></div>:<div className="receipt-list">{orders.map(o=><div className="receipt-row" key={o.id}><div className="receipt-icon"><Receipt size={19}/></div><div><strong>{o.service_name||"YN Studio Order"}</strong><span>{o.public_order_number||`Order #${o.id}`}</span></div><div className="receipt-total">${Number(o.total||0).toFixed(2)}</div><button className="receipt-download" onClick={()=>download(o)}><Download size={16}/></button></div>)}</div>}</section>}
